services:
  db:
    image: postgres:18
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  prestart:
    image: ${DOCKER_IMAGE?Variable not set}:${TAG-latest}
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
        # restart: true
    command: bash scripts/prestart.sh
    env_file:
      - .env

  backend:
    image: ${DOCKER_IMAGE?Variable not set}:${TAG-latest}
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
        # restart: true
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    command: sleep infinity

  notebook:
    image: ${DOCKER_IMAGE?Variable not set}:${TAG-latest}
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        # restart: true
      prestart:
        condition: service_completed_successfully
    command:
      - sh
      - -c
      - >
        uv sync --group notebook &&
        uv run --group notebook jupyter lab
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --allow-root
        --notebook-dir=/notebooks
    ports:
      - 8888:8888
    volumes:
      - ./backend:/app
      - /app/.venv
      - ./notebooks:/notebooks

volumes:
  app-db-data:
