"""initial migration

Revision ID: 20b69d79d99a
Revises: 
Create Date: 2026-06-09 19:49:52.030191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b69d79d99a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('objectid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.String(length=15), nullable=True),
    sa.Column('owner1', sa.String(length=255), nullable=True),
    sa.Column('owner2', sa.String(length=255), nullable=True),
    sa.Column('tax_district', sa.String(length=255), nullable=True),
    sa.Column('class_code', sa.String(length=255), nullable=True),
    sa.Column('mail_st_no', sa.String(length=255), nullable=True),
    sa.Column('mail_st_name', sa.String(length=255), nullable=True),
    sa.Column('mail_st_type', sa.String(length=255), nullable=True),
    sa.Column('mail_2nd_addr', sa.String(length=255), nullable=True),
    sa.Column('mail_2nd_addt', sa.String(length=255), nullable=True),
    sa.Column('mail_city', sa.String(length=255), nullable=True),
    sa.Column('mail_state', sa.String(length=255), nullable=True),
    sa.Column('mail_zip', sa.String(length=255), nullable=True),
    sa.Column('mail_country', sa.String(length=255), nullable=True),
    sa.Column('legal_descr', sa.String(length=255), nullable=True),
    sa.Column('subdivision', sa.String(length=255), nullable=True),
    sa.Column('acreage', sa.Float(), nullable=True),
    sa.Column('legal_residence', sa.String(length=255), nullable=True),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.Column('agr', sa.String(length=255), nullable=True),
    sa.Column('deed_book_page', sa.String(length=255), nullable=True),
    sa.Column('plat_book_page', sa.String(length=255), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('recorded_date', sa.DateTime(), nullable=True),
    sa.Column('doc_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_records_objectid'), 'parcel_records', ['objectid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcel_records_objectid'), table_name='parcel_records')
    op.drop_table('parcel_records')
    # ### end Alembic commands ###
