"""initial_table

Revision ID: a5a5855e3448
Revises: 
Create Date: 2026-05-27 15:10:23.221344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a5855e3448'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('features_sde_p_poly_parcel_objectid', sa.Integer(), nullable=False),
    sa.Column('features_sde_p_poly_parcel_pid', sa.String(length=15), nullable=True),
    sa.Column('features_sde_p_poly_parcel_gpin', sa.String(length=16), nullable=True),
    sa.Column('features_sde_p_poly_parcel_acres_cal', sa.Float(), nullable=True),
    sa.Column('features_sde_cama_owner1', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_owner2', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_tax_district', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_class_code', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_st_no', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_st_name', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_st_type', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_2nd_addr', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_2nd_addt', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_city', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_state', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_zip', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_mail_country', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_legal_descr', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_subdivision', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_acreage', sa.Float(), nullable=True),
    sa.Column('features_sde_cama_legal_residence', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_other', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_agr', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_deed_book_page', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_plat_book_page', sa.String(length=255), nullable=True),
    sa.Column('features_sde_cama_sale_price', sa.Float(), nullable=True),
    sa.Column('features_sde_cama_recorded_date', sa.DateTime(), nullable=True),
    sa.Column('features_sde_cama_doc_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_records_features_sde_p_poly_parcel_objectid'), 'parcel_records', ['features_sde_p_poly_parcel_objectid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcel_records_features_sde_p_poly_parcel_objectid'), table_name='parcel_records')
    op.drop_table('parcel_records')
    # ### end Alembic commands ###
