"""initial parcel

Revision ID: bdfc8c62518d
Revises: 
Create Date: 2026-06-19 13:56:16.738191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfc8c62518d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('pid', sa.String(length=15), nullable=False),
    sa.Column('objectid', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('owner1', sa.String(length=255), nullable=True),
    sa.Column('owner2', sa.String(length=255), nullable=True),
    sa.Column('tax_district', sa.String(length=255), nullable=True),
    sa.Column('class_code', sa.String(length=255), nullable=True),
    sa.Column('mail_st_no', sa.String(length=255), nullable=True),
    sa.Column('mail_st_name', sa.String(length=255), nullable=True),
    sa.Column('mail_st_type', sa.String(length=255), nullable=True),
    sa.Column('mail_2nd_addr', sa.String(length=255), nullable=True),
    sa.Column('mail_2nd_addt', sa.String(length=255), nullable=True),
    sa.Column('mail_city', sa.String(length=255), nullable=True),
    sa.Column('mail_state', sa.String(length=255), nullable=True),
    sa.Column('mail_zip', sa.String(length=255), nullable=True),
    sa.Column('mail_country', sa.String(length=255), nullable=True),
    sa.Column('legal_descr', sa.String(length=255), nullable=True),
    sa.Column('subdivision', sa.String(length=255), nullable=True),
    sa.Column('acreage', sa.Float(), nullable=True),
    sa.Column('legal_residence', sa.String(length=255), nullable=True),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.Column('agr', sa.String(length=255), nullable=True),
    sa.Column('deed_book_page', sa.String(length=255), nullable=True),
    sa.Column('plat_book_page', sa.String(length=255), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('recorded_date', sa.DateTime(), nullable=True),
    sa.Column('doc_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_parcels_acreage'), 'parcels', ['acreage'], unique=False)
    op.create_index(op.f('ix_parcels_class_code'), 'parcels', ['class_code'], unique=False)
    op.create_index(op.f('ix_parcels_mail_state'), 'parcels', ['mail_state'], unique=False)
    op.create_index(op.f('ix_parcels_mail_zip'), 'parcels', ['mail_zip'], unique=False)
    op.create_index(op.f('ix_parcels_objectid'), 'parcels', ['objectid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_objectid'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_mail_zip'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_mail_state'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_class_code'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_acreage'), table_name='parcels')
    op.drop_table('parcels')
    # ### end Alembic commands ###
