"""add parcel geometry fields

Revision ID: e1a7d5f373ae
Revises: bdfc8c62518d
Create Date: 2026-06-21 19:53:34.056555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a7d5f373ae'
down_revision: Union[str, Sequence[str], None] = 'bdfc8c62518d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('geometry_esri_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parcels', sa.Column('geometry_wkid', sa.Integer(), nullable=True))
    op.add_column('parcels', sa.Column('computed_area_sqft', sa.Float(), nullable=True))
    op.add_column('parcels', sa.Column('computed_acreage', sa.Float(), nullable=True))
    op.add_column('parcels', sa.Column('area_computation_method', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_parcels_acreage'), table_name='parcels')
    op.alter_column(
        "parcels",
        "acreage",
        new_column_name="deeded_acreage",
        existing_type=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "parcels",
        "snapshot_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_index(op.f('ix_parcels_computed_acreage'), 'parcels', ['computed_acreage'], unique=False)
    op.create_index(op.f('ix_parcels_deeded_acreage'), 'parcels', ['deeded_acreage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_deeded_acreage'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_computed_acreage'), table_name='parcels')
    op.drop_column('parcels', 'area_computation_method')
    op.drop_column('parcels', 'computed_acreage')
    op.drop_column('parcels', 'computed_area_sqft')
    op.drop_column('parcels', 'geometry_wkid')
    op.drop_column('parcels', 'geometry_esri_json')
    op.alter_column(
        "parcels",
        "deeded_acreage",
        new_column_name="acreage",
        existing_type=sa.Float(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_parcels_acreage"),
        "parcels",
        ["acreage"],
        unique=False,
    )
    op.alter_column(
        "parcels",
        "snapshot_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
